### ISSUE TITLE
`cpud` command hang when `dsEnabled` is false

### ISSUE THREAD

**Issue by Lencerf** [u-root/cpu#144]
In https://github.com/u-root/cpu/commit/ae73b13fffdd4e69716bf2388022ff4938994bbd, 
If `dsEnabled` is false, function `DsRegister` will never be called, thus no thread will receive from `tenChan`. On the other hand, in `handler()`, there is `tenChan <- 1` at the beginning and end of the function. Since `tenChan` has capacity 1, the second `tenChan <- 1` will block the function forever.

**Comment by ericvh** [comment]
fix here, but testing first.  Sorry, not sure how this slipped through -- I thought I tested the absence of dsEnabled, but it was probably earlier in the series (tenants was one of the last things I added)

https://github.com/u-root/cpu/commit/b271cc3fd2b947e12a2a7fbefc706ba21b8403b7

**Comment by ericvh** [comment]
okay, this fix seems to work: https://github.com/u-root/cpu/commit/542c66e214f50cbf7cff3566dd4dfe40655cb5d8

Let me know if that looks roughly correct or if you'd rather it be done a different way.  I'll rebase and collapse it if you think that looks right.

**Comment by ericvh** [comment]
fixed via reversion of affected code.
