### ISSUE TITLE
What are the other options if I have systemd

### ISSUE THREAD

**Issue by Rubo3** [u-root/cpu#59]
Running `cpud -d -remote` I get:

    2022/02/07 18:25:05 CPUD:Warning: unshare failed (operation not permitted). There will be no private 9p mount if systemd is there
    2022/02/07 18:25:05 CPUD:Warning: tmpfs mount on /tmp (operation not permitted) failed. There will be no 9p mount
    2022/02/07 18:25:05 
    CPUD:Args [cpud -d -remote] pid 9903 *runasinit false *remote true
    2022/02/07 18:25:05 
    CPUD:Running as remote
    2022/02/07 18:25:05 CPUD:namespace is "/lib:/lib64:/usr:/bin:/etc:/home"
    2022/02/07 18:25:05 CPUD:Dial 127.0.0.1:
    2022/02/07 18:25:05 CPUD:Dial 9p port: dial tcp4 127.0.0.1:0: connect: connection refused

First things first: since on my system (Arch Linux) I run systemd, what other options are there? Do I need to set up a virtual machine?

**Comment by rminnich** [comment]
Try running:
cpud -d -init

It has fixes for systemd breaking private mounts.

**Comment by Rubo3** [comment]
It works, thanks!
