### ISSUE TITLE
invalid use of WriteAt on file opened with O_APPEND

### ISSUE THREAD

**Issue by brho** [u-root/cpu#64]
After running a command with bash or sh and hitting ctl-d or type 'exit', I get that error.  If i hit ctl-d immediately, i do not.  if the command is 'exit', i also get it.

seems like any time i issue any command, even 'exit', i'll get the error.  but not if if i hit ctl-d first.  (and not if i get some other error, as in the other bug, where ctl-c followed by ctl-d gave a different error).

e.g.
```
$ ./cpu TARGET sh
sh-5.1# ls
cpu	  cpu_darwin.go  cpu_linux.go  getattr_darwin.go  srv.go
cpu9p.go  cpu.go	 doc.go        getattr_linux.go
sh-5.1# exit
exit
2022/03/04 16:27:08 unknown error: os: invalid use of WriteAt on file opened with O_APPEND
                                                                                          $ 

$ ./cpu TARGET sh
sh-5.1# exit
exit
2022/03/04 16:27:32 unknown error: os: invalid use of WriteAt on file opened with O_APPEND
                                                                                           $ 

(i hit ctl-d on this one)
$ ./cpu TARGET sh
sh-5.1# 
exit

```

**Comment by rminnich** [comment]
I've been trying to find that one and can't. I think I need to do a log.Panicf on that error. It's just so flaky.

**Comment by rminnich** [comment]
This is some weird race that I don't get yet. Help needed.

**Comment by brho** [comment]
ah, so on my system, sh is symlinked to bash, just without a lot of bashrc processing or whatever.

anyway, from strace and from running with -d, the file is bash_history, opened with O_APPEND.  WriteAt(.., offset) apparently doesn't like that.
